on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Json-lint
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: json-lint
      uses: ./
